### ISSUE TITLE
No disarm trap voice command in tacspeak

### ISSUE THREAD

**Issue by madmaximus101** [jwebmeister/tacspeak#4]
Currently as far as I know there is no voice command to disarm traps? From recent memory this is the only option i can recall having to order teammates to disarm trap. If i find any other command menu options for this i will let you know. Thankyou

![20231217150649_1](https://github.com/jwebmeister/tacspeak/assets/154042211/0df6b5c1-d384-4054-bf1a-016487ea4613)

**Comment by jwebmeister** [comment]
Thanks for the screenshot. I'll update soon.

So annoying that it's inserted halfway in the list of door options, so all the keys corresponding to the commands for wedge, cover and open are completely different if it's a door with a trap on it or not. /endrant
I'm hoping Void notices Tacspeak and looks to improve the command menu for a better player experience when using Tacspeak, or other speech recognition software, or in the base game in general. /reallyendrant

**Comment by jwebmeister** [comment]
Example spoken commands (not exhaustive):
- "blue team disarm that door"
- "red team wedge that trapped door" (for a trapped door)
- "gold cover that trapped door" (for a trapped door)
- "gold cover the door" (for a un-trapped door)

The command keys will shift appropriately for the affected commands (wedge, cover, open / close door) if the user says it's a "trapped" door, or it will default to the command keys for an non-trapped door if the user does not say "trapped".

Will package as release 0.1.2 very soon.

**Comment by madmaximus101** [comment]
wow that was quick! amazing work mate :)

**Comment by jwebmeister** [comment]
Done! [Release 0.1.2](https://github.com/jwebmeister/tacspeak/releases/tag/0.1.2)

**Comment by madmaximus101** [comment]
> Done! [Release 0.1.2](https://github.com/jwebmeister/tacspeak/releases/tag/0.1.2)

**Comment by madmaximus101** [comment]
> > Done! [Release 0.1.2](https://github.com/jwebmeister/tacspeak/releases/tag/0.1.2)

Confirmed working. Found a door with trap. A.I teammates were unaware trap existed so option to disarm didnt exist. Ordered teammate to mirror the door then the option to disarm trap appeared. Used the command "disarm trap" and it worked instantly without issue!

**Comment by madmaximus101** [comment]
Mate i am strongly of the opinion you have something genuinely amazing
here. Something you could actually make some money off. Create some sort of
base program - with forks for different games, addons etc - unsure how
you'd go about that but hey, ideas! This speech app you've made is beyond
anything I've tried before. It probably helps that I'm aussie, probs why
works so gosh darn well for me heh. If you do decide to go further, maybe
involve others with an American accent or English, European, South African,
Asian etc. Flesh out the recognition. I have nothing of note or
significance to contribute to your endeavor, as i have very
rudimentary understanding of .py files and the logic, programming
etc. Consider me a blown away, very thankful user of your software. Amazing
mate. Your doing an awesome thing.

**Comment by jwebmeister** [comment]
> Mate i am strongly of the opinion you have something genuinely amazing here. Something you could actually make some money off. Create some sort of base program - with forks for different games, addons etc - unsure how you'd go about that but hey, ideas! This speech app you've made is beyond anything I've tried before. It probably helps that I'm aussie, probs why works so gosh darn well for me heh. If you do decide to go further, maybe involve others with an American accent or English, European, South African, Asian etc. Flesh out the recognition. I have nothing of note or significance to contribute to your endeavor, as i have very rudimentary understanding of .py files and the logic, programming etc. Consider me a blown away, very thankful user of your software. Amazing mate. Your doing an awesome thing.

The heavy lifting is being done by [Dragonfly](https://github.com/dictation-toolbox/dragonfly) and [Kaldi Active Grammar](https://github.com/daanzu/kaldi-active-grammar). Both are free open-source projects, and amazing. The use + license of KAG requires this project be released open-source under the same license, not that I would've chosen to do otherwise.  

Donations are an option, and would very much be appreciated, but / and I'll keep fleshing out Tacspeak as long as I can.

The mechanism of how KAG activates / deactivates parts of the model is how it works so well where others fall down for this use-case, or at least that's what I believe from researching, testing and comparing various models.
The model hasn't been trained on particularly Australian accents as far as I'm aware. I believe it's mostly open source speech datasets, though I admit to not knowing all the details.  Model details are [here](https://github.com/daanzu/kaldi-active-grammar/blob/master/docs/models.md).
